spring.application.name=pet-project

#DB
spring.datasource.url=jdbc:postgresql://localhost:5431/event_app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database=postgresql
spring.jpa.show-sql=true